### ISSUE TITLE
Bissell does not offer any logging to indicate that it has started

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/bissell#1]
Unlike other services, when ran, Bissell does not offer any logging to indicate that it has started.

This adds complication to using Bissell in automated tests as the setup code has to resort to polling it with requests in order to determine if it is ready to use.

**Comment by jrandall** [comment]
surely the code that sets up the test will have an easier time polling with http requests than trying to parse the stderr from bissell? that would also be fairly pointless as a 100ms sleep would have the same effect. bissell starts up in a fraction of a second. 

add logging if you want, but I think it's more trouble than its worth.

**Comment by colin-nolan** [comment]
In the past, I've relied on a "I'm ready to go!" type message as my thinking has been that the service is in a better position that the observer to say whether or not it is ready. Without an understanding of the internals of a service, the observer cannot truely say that, if a particular endpoint is successfully prodded, then the service is fully functional. i.e. just because endpoint A is ready, it does not imply endpoint B is too; it could be a different "microservice", for example.

I appreciate that the point is largely academic though: in most cases, a success response from an endpoint will require everything to be working.

As for sleeping and hoping everything will be ready when we wake up - that is how iRODS works (or at least used to) and it is subsequently a massive PITA. Either time is wasted sleeping when everything is ready or not enough time is allocated and it's not ready!

Given that Bissell is so simple, I'll forget my over-engineered, theoretical woes and just poll the thing ;).

**Comment by jrandall** [comment]
Fixed by 7e25e041
